name: test, build, development
on: 
  push:
    branches:
      - development
jobs:
  build_docker:
    name: build and push to dockerhub
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v3
    - name: docker build
      run: docker build -t peacechopath/lokasani:1.1.0 .
    - name: docker login
      uses: docker/login-action@v3
      with: 
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: push to docker hub
      run: docker push peacechopath/lokasani:1.1.0
